### ISSUE TITLE
not really an issue 

### ISSUE THREAD

**Issue by jiiiit** [noeRls/medal-downloader#18]
I don't  know if you still update it but, is there a way you could make it so it downloads every video even if the title is "Untitled"? I'm just asking because I haven't found another option besides using yours and I hate having to rename videos constantly to be able to download. Thanks even if you can't

**Comment by noeRls** [comment]
Hey, yes this project is still active, can you give me your username so I can create and test this feature?

**Comment by jiiiit** [comment]
Yeah I made a newer account so you could try, username is x0i

**Comment by noeRls** [comment]
This has been implemented v1.3.0
